### ISSUE TITLE
check F RW

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#107]
see comments in code, but the RW in F in the TIM may not be adequately coded

**Comment by jonathanderoba** [comment]
Comment in the code was:
//DG
// IS THIS CORRECT or do we need a separate F_init and replace log_F with F_year here?-DG
//DG

We had a separate F_init by virtue of an if(y==1) statement just above the comment.  No need to replace log_F with F_year because log_F are the actual parameters and e^log_F=F_year.  If we did replace log_F with F_year (I did this), then F will change linearly from the F in year=1 with slope=F_rho.  For example, if F_rho=1, then F is the same in all years and equal to F in year=1.  Replacing log_F with F_year also results in a bunch of log_F parameters that have no way to affect the likelihood and so non-convergence.  I ran the model with RW F and it worked, although I could not estimate F_rho.  Trying RW F also did not fix any of the scale issues we've been having (October 13, 2017).  Results were nearly identical.
