### ISSUE TITLE
recruitment likelihood

### ISSUE THREAD

**Issue by jonathanderoba** [KatelynBosley/SPASAM#121]
Take a hard look at the likelihood for recruitment and make sure it's correct.  Someone else commented about his in the EM (hakeish) code, and I agree that something might be wrong.  I just haven't gotten to it yet and so it's an official Issue so we don't forget.

**Comment by GreatDana** [comment]
I put in the likelihood for estimating sigma_r, which is probably a mistake since we may not be trying to do that (but since CAPAM is a recruitment paper, maybe we should). I doubt it will make a big difference, and its not a true likelihood anyway, its just a penalty so people seem to use a lot of variations. I would try:

    rec_like      = norm2(log_rec_dev+sigr*sigr/2.)/(2.*square(sigr)) ;


Cheers,
Dana

**Comment by dgoethel** [comment]
i changed likelihood to penalize devs from SR curve (or R_ave) and made rec_devs a bounded_dev_vector

worth checking these to see if they are ok

**Comment by GreatDana** [comment]
Seems like things are working OK, I changed recruit devs to a devs matrix instead of an end to end dev_vector
