### ISSUE TITLE
code harvest allocation based on Rec index/Survey index

### ISSUE THREAD

**Issue by KatelynBosley** [KatelynBosley/SPASAM#21]
Need to add code to re-define next years F/u  based on index values. Should maybe add a switch to refer to which survey is being used to allocate harvest to different areas.

**Comment by dgoethel** [comment]
I think something like this would work (the switch needs to be after each survey calc and before each NR iteration):

 It seems like all we really need to do is put a switch in for something like alter_TAC_data (=0,1) to allow the input_TAC (or u) to be altered based on the input data stream (so maybe a second switch to define what data to use in that alteration calc).  I think something along the lines of

if(alter_TAC_data==TRUE)
{
if(alter_data==survey_numbers)
{
input_TAC(j,r,x)=input_TAC(j,r,x)*apport_region_survey(j,r,y);
}
}

We also need to note that the input TAC or u needs to be the total value but have that input used for each region (ie if the total TAC is 100 then the input_TAC would be (100 100) otherwise would be apportioning less than the total TAC).

**Comment by dgoethel** [comment]
Working on this now (3/15)
