### ISSUE TITLE
For Annual Meeting: Manuscript 2: Clean up report section (of code)

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#41]
needs to be updated with new values and reporting out observed values to read into estimation model

**Comment by brianlangseth** [comment]
Account for wonky handling by R of output from report file for 6d arrays

**Comment by brianlangseth** [comment]
For langseth... this is an example of a for loop you need to change the order of an array, and then bring it back if needed , this example is moving the fish in the natage matrix, and then reassiging them to the natage matrix.

for(j=1;j<=10;j++){
for (k=1;k<=nareas;k++) {
AMnatage_f(i,k,j)=natage_f(k,i,j);
AMnatage_m(i,k,j)=natage_m(k,i,j); }
AMnatage_f(i)=trans(phi(2))*AMnatage_f(i) ;
AMnatage_m(i)=trans(phi(2))*AMnatage_m(i) ;
for (k=1;k<=nareas;k++) {
natage_f(k,i,j)=AMnatage_f(i,k,j);
natage_m(k,i,j)=AMnatage_m(i,k,j); }}

**Comment by brianlangseth** [comment]
R doesnt handle 5d AND 6d arrarys. Reorganized so that variables I wished to report over were in the beginning of the variable definition, and thus could output over using 

variable[1st variable to output over][2nd variable to output over] 

Also combined over ages for some of the migration arrays to reduce dimensionality, since there is no age specific movement.

Need to test output before uploaded and submitting pull request.

**Comment by brianlangseth** [comment]
Fixed issue for both the Spatial BRP folder and the Tag Integrated Folder. Modified the tpl for both following the steps below. 

Things added to SPASAM\Spatial_BRP_project\Operating_Model:

1.	Added report out of “nfleets_survey”

2.	5d and 6d arrays
Reorganized all 6d arrays that aren’t temporary: 
renamed variables to start with ‘ro’, and redefined so that the first two dimensions are population from and region, as opposed to population from and population to. For 6d vital arrays, dimensions were already population from and region, so did not need to reorganize. Outputted as 4d arrays indexed by the region number (region 1 = pop 1 region 1; region 2 = pop 1 region 2 (or pop 2 region 1 is single regions per pop; etc.) with naming convention of “_X” at the end where X is the region number, which required indexing over region and population (from) dimensions. 

Outputted all 5d arrays that aren’t temporary:
outputted as 4d arrays indexed by the population number with naming convention of “_Y” at the end where Y is the population number of the first (population from) dimension, and “alt_” at the beginning. For input_T, although it’s a 5d array, I had to index over population and region because I was getting reading issues into R when indexing only over pop, thus output for it is in a 3d array, and it’s named with “alt_” in the beginning and “_X” at the end where X is the region number.

Hence, anything starting with “ro_” had its dimensions reorganized and reduced, whereas anything starting with “alt_” only had its dimensions reduced.


Things added to SPASAM\Tag_integrated_model\Operating_Model:

1.	Added report out of “nfleets_survey”

2.	Removed extra report out of “nages”

3.	Remove report out of “tag_prop_final” and “OBS_tag_prop” since these are 5d arrays and I report them out with formatting described in point 5.

4.	Removed four more variables in the report section that would cause issues when reading in the report file because they were 5d arrays. These were true_survey_fleet_bio_overlap, OBS_survey_fleet_bio_overlap, yield_region_fleet_overlap, OBS_yield_region_fleet_overlap. These variable were included in point 5, below.  

5.	5d and 6d arrays
Reorganized all 6d arrays that aren’t temporary: 
renamed variables to start with ‘ro’, and redefined so that the first two dimensions are population from and region, as opposed to population from and population to. For 6d vital arrays, dimensions were already population from and region, so did not need to reorganize. Outputted as 4d arrays indexed by the region number (region 1 = pop 1 region 1; region 2 = pop 1 region 2 (or pop 2 region 1 is single regions per pop; etc.) with naming convention of “_X” at the end where X is the region number, which required indexing over region and population (from) dimensions. 

Outputted all 5d arrays that aren’t temporary:
outputted as 4d arrays indexed by the population number with naming convention of “_Y” at the end where Y is the population number of the first (population from) dimension, and “alt_” at the beginning. For input_T, although it’s a 5d array, I had to index over population and region because I was getting reading issues into R when indexing only over pop, thus output for it is in a 3d array, and it’s named with “alt_” in the beginning and “_X” at the end where X is the region number.

6.	7D tagging arrays
Outputted as 4d arrays indexed by the region number (region 1 = pop 1 region 1; region 2 = pop 1 region 2 (or pop 2 region 1 is single regions per pop; etc.) and the year of tag releases, with naming convention of “_regX_relZ” at the end where X is the region number, which required indexing over region and population (from) dimensions, and Z is the release year

Hence, anything starting with “ro_” had its dimensions reorganized and reduced, whereas anything starting with “alt_” only had its dimensions reduced.


Issue is now closed.
