### ISSUE TITLE
Manuscript 2: Alternate assessment models

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#50]
Do we want to include a fully spatially-aggregated and/or Fleets-as-Areas models in our study?  If so how do we handle data aggregation for each model type....

**Comment by jonathanderoba** [comment]
Yes.  This was discussed at Newport meeting.  Data is simulated at the finest spatial scales and can then be summed across those finer scales to create aggregated observations.  For example, catch-at-age (units of numbers of fish) from each region can be summed to get aggregate observation, and this would "self-weight" because areas with more catch will implicitly be more represented in the age-comps (as it should be).
