### ISSUE TITLE
For Annual Meeting: Validate RNG Approach 

### ISSUE THREAD

**Issue by dgoethel** [KatelynBosley/SPASAM#63]
Does it give fully independent RN sequences for each fleet

**Comment by jonathanderoba** [comment]
I wasn't sure whether your concern was about the randn function itself, populating the x_RN arrays with single calls to the random number generator, the seed, or the implementation.  But, this was a pleasant excuse for me to get back into ADMB, which I haven't done in awhile.  So, I isolated the code to just fill the F_RN array with randn numbers (I used F_RN, but yield_RN and others are analogous).  I confirmed that the numbers are independent among all elements of the array.  I then just studied the code where the x_RN arrays are applied and I saw no reason to think that the iid values were misapplied in a way that would create unwanted correlation, although I did not test this explicitly.

One thing for the future that may be a separate issue is that the OM currently has no simulation loop (e.g., used to generate multiple datasets for the EM).  If/when this is added, we'll have to remember to systematically vary our start seeds for each simulation so that we don't end up with the same sequence of random numbers for each simulation.
