### ISSUE TITLE
MS1: How do we calculate Bratio when using Rec_type = 1

### ISSUE THREAD

**Issue by KatelynBosley** [KatelynBosley/SPASAM#84]
If Rec_type = 1, Bratio returns inf because SSB_zero = 0 with current SPR calcs.

**Comment by jonathanderoba** [comment]
I'll add this option to the SPR calcs today (May 19).  Standby for pull request.

JJD

**Comment by jonathanderoba** [comment]
I'm fairly certain that the SPR calcs are identical regardless of the rec_type option chosen.  The master I started with had the entire spr calcs section inside an if(rec_type==2) statement.  But, the only calculation unique to rec_type==2 (i.e., BH) is the alpha and beta.  So, I moved the if(rec_type==2) statement so that it only included the alpha and beta calculations, while all the other spr calcs (spr, SSB_zero) will be the same regardless of the rec_type chosen.

**Comment by GreatDana** [comment]
This opens up another question... that I haven't figured out yet. Are we calculating B100 here to compare what? And I don't think we should be comparing B_zero as estimated by Beverton-Holt parameters to B100. If we are using B100 as a basis of looking at SPR reference points, we will need those calcs added into the estimation model, and these are the tricky calculations that we have been dealing with for sablefish for how SPR/movement interact. Maybe we can discuss at our next call.

**Comment by KatelynBosley** [comment]
I think we dealt with this a while ago.
